### ISSUE TITLE
error rolling on loot table

### ISSUE THREAD

**Issue by hematic** [jopeek/fvtt-loot-sheet-npc-5e#319]
On version 3.5.10

Trying to roll on a loot table generates :

LootProcessor.js:43 Uncaught (in promise) TypeError: this.rawResults is not iterable
[Detected 1 package: lootsheetnpc5e]
    at LootProcessor.buildResults (LootProcessor.js:43:35)
    at async Function.addLootToTarget (ActorHelper.js:171:17)
    at async Function.seedItemsToActors (LootSeeder.js:36:109)
    at async SheetListener.inventoryUpdateListener (SheetListener.js:164:62)

**Comment by hematic** [comment]
Nevermind, apparently this is caused if you don't set a roll method on the loot table itself :)
